### PR TITLE
feat: [NMP-30] Feature** setup vite pwa

### PR DESCRIPTION
**Pull request by kcaparas1630**
# Description

Installed vite-plugin-pwa to the current frontend application and configured an initial setup for vite pwa with registerType to autoUpdate to specify registration type for the service worker.

## Type of changes

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments
If there is other configuration that I need to add into this please let me know! Also, pulling from recent branch to a new feature branch is still confusing to me, so I hope I don't make any merge conflicts!

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-sustainment-capstone-2024-44-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-sustainment-capstone-2024-44-frontend.apps.silver.devops.gov.bc.ca/api)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-sustainment-capstone-2024/actions/workflows/merge.yml)

### CODE REVIEW

**Review by LocalNewsTV — COMMENTED** [review]
In pulling this on my own device the `npm run lint` didn't run until I installed two more dependencies not in your `package.json` outlined by the script 
`npm install eslint-plugin-react@latest --save-dev`
`npm install eslint-plugin-jsx-a11y@latest --save-dev`

This will also flag a bunch of issues since the default vite template doesn't follow AirBnB styling. but because its small and you started early, this is minimal refactoring. You'll be deleting 95% of it anyways because its just boilerplate.

Ultimately you're probably going to want to disable some of the rules, it's not a one size fits all, and you're using TS over JS 

This file is a year old, but here is some of the overrides we used when we were doing Capstone [You can see them here](https://github.com/bcgov/citz-imb-wayfinder/blob/main/src/frontend-pwa/.eslintrc.json)

**Review by LocalNewsTV — COMMENTED** [review]
You'll need a manifest to have a proper vite PWA. 
Here's the docs https://vite-pwa-org.netlify.app/guide/

You can verify your PWA is valid by running `npm run build` -> `npm run preview` 
If you open the browser in `Chrome`, you'll be given an option to install your application
If you're using a Mac PWA support is only on `Safari`

**Comment by kcaparas1630** [comment]
Been able to download the web application in my local device, please test it out on your own device before reviewing thanks!

**Review by LocalNewsTV — APPROVED** [review]
Installs as expected, good work :) 

CLI recommends adding a theme_color that's missing to make installable, but can install without. Can either remediate with defauling a value to the key, or deal with in the future

image

**Review by GDamaso — APPROVED** [review]
Worked for me after deleting package-lock.json and node_modules
README would be nice to instruct building before the preview and listing ports being used

**Comment by kcaparas1630** [comment]
Added name, description, and theme_color. Will merge now.

**Pull request merged**
